export const eventData = [
  {
    id: 1,
    title: "ibis Otel Ticarət forumu",
    date: "2025-05-30",
    time: "10:00",
    imagePath: "../public/ibis.png",
    link: "https://may2025iif.birgekod.az/",
  },
  {
    id: 2,
    title: "Baku Marriott Hotel Boulevard1",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 3,
    title: "Baku Marriott Hotel Boulevard2",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 4,
    title: "Baku Marriott Hotel Boulevard3",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 5,
    title: "Baku Marriott Hotel Boulevard4",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 6,
    title: "Baku Marriott Hotel Boulevard5",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 7,
    title: "Baku Marriott Hotel Boulevard6",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 8,
    title: "Baku Marriott Hotel Boulevard7",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 9,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 10,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 11,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 12,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 13,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 14,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 15,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 16,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 17,
    title: "Baku Marriott Hotel Boulevard8",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
  {
    id: 18,
    title: "Baku Marriott Hotel Boulevard17",
    date: "2025-02-11",
    time: "10:00",
    imagePath: "../public/marriot.png",
    link: "https://fevral2025iif.birgekod.az/",
  },
];
